version: '3'

services:
  mailserver:
    build: .
    container_name: mailserver
    ports:
      - "25:25"
      - "143:143"
      - "110:110"
    volumes:
      - maildata:/var/mail

volumes:
  maildata:
